### ISSUE TITLE
The implementation option must be passed to the Sass task

### ISSUE THREAD

**Issue by cichy380** [them-es/themes-starter#1]
When I run `grunt watch` and when I did change in **main.scss** I got error:
```
File "main.scss" changed.
Running "sass:dist" (sass) task
Fatal error: The implementation option must be passed to the Sass task
```

**Comment by sangtlee** [comment]
I was able to correct by:

- Adding node-sass dependency to package.json:
`"node-sass": "*",`
- Re-run npm install
- Update Gruntfile.js, add:
`const sass = require('node-sass');`
and to sass task:
`options: {
	implementation: sass,
	sourceMap: true
},`

**Comment by them-es** [comment]
@cichy380 and @sangtlee 

Thanks for raising this issue and for providing a bugfix. ```package.json``` and ```Gruntfile.js``` have been updated in the latest release v2.1.0

**Comment by oliver-007** [comment]
tnks bro. it works perfectly
