### ISSUE TITLE
New user of this wonderful starter theme and upgrade, add zip package creation

### ISSUE THREAD

**Issue by dantahoua** [them-es/themes-starter#10]
Hello!
I'm glad to have find this theme. Was using similar theme based on Foundation (FoundationPress, now deprecated) but as Bootstrap 5.x is more robust and have more features I was looking for a starter theme without bloat!
 
Not really an issue, but some suggestion:
-Upgrade to Bootstrap 5.1.3 (I changed it in the package.json and it seems alright for now).
-Add a script to generate a zip package (without source so it's light) we could upload directly to our wordpress theme folder. Very helpfull when we update the online/production website. 
Something like:
```
// Create a .zip archive of the theme
function archive() {
  var time = dateFormat(new Date(), "yyyy-mm-dd_HH-MM");
  var pkg = JSON.parse(fs.readFileSync('./package.json'));
  var title = pkg.name + '_' + time + '.zip';

  return gulp.src(PATHS.package)
    .pipe($.zip(title))
    .pipe(gulp.dest('packaged'));
}
```
with 
```
 # Paths for the package task to include/exclude in .zip archive
  package:
    - "**/*"
    - "!**/node_modules/**"
    - "!**/packaged/**"
    - "!**/src/**"
    - "!**/codesniffer.ruleset.xml"
    - "!**/composer.json"
    - "!**/composer.lock"
    - "!**/config.yml"
    - "!**/config.default.yml"
    - "!**/gulpfile.babel.js"
    - "!**/package.json"
    - "!**/package-lock.json"
    - "!**/webpack.config.js"

```
I just copied here what I add in Foundation press without adapting it to your folder structure but it just for the idea! :)

**Comment by them-es** [comment]
Hi @dantahoua,

thanks for your kind words. Bootstrap now has been updated in `package.json` to the latest release. No code changes are required with this minor release.

Regarding your second suggestion. If you need to create a custom **Starter Theme ZIP package** you can try out the Theme Generator from our website: https://them.es/starter-bootstrap/
It automatically generates custom function names and includes just what you need to get started.

If you want to programmatically upload your theme to production (without the development bloat), a Gulp deployment task runner like https://github.com/morris/vinyl-ftp could be added as a new Gulp task. But deployment tasks are out of scope for this Starter Theme and need to be included by yourself.
