### ISSUE TITLE
Latency with Browser reload

### ISSUE THREAD

**Issue by oueryemchi** [them-es/themes-starter#16]
Hi guys,

I like the theme, well done!

I am running Wordpress with the them.es theme in Docker and have every working, but Browser reload takes a while before refreshing (up to 3 sec delay).

UPDATE: it is not the Browser reload, it is the compiling of the SCSS that takes long..
`[21:34:04] Finished 'build_css' after 4.79 s`

Anything I missed?

Thanks

**Comment by them-es** [comment]
Hi @oueryemchi,

thanks for your kind words. Glad the Starter theme is useful for you.

Regarding your question. Unfortunately we can't provide support for external libraries or fix issues that are Docker specific. But you could try to experiment with the dependencies in `package.json` - i.e. by modifying the version numbers or even replacing the SASS compiler with a different (faster?) compiler.

Good luck with debugging the issue.
