### ISSUE TITLE
 Why both gulp and webpack ??

### ISSUE THREAD

**Issue by vahidalvandi** [them-es/themes-starter#17]
Why does he have both? If the webpack is not used

**Comment by them-es** [comment]
One word: _flexibility_. Actually Webpack is implemented and it allows to enhance and bundle a custom WordPress Theme with further JS libraries which don't come with Bootstrap. E.g. a special carousel, lightbox feature, autocompleter, etc.
Furthermore you can just import the Bootstrap modules you need to reduce the overall filesize of your project as described here https://getbootstrap.com/docs/5.1/getting-started/webpack/#importing-javascript

But in the end this is a Starter Theme. If you don't need Webpack in your project, just remove it.
