### ISSUE TITLE
JQuery don´t work on latest Wordpress Version

### ISSUE THREAD

**Issue by bernardinosousa** [them-es/themes-starter#2]
Hi,
It´s possible to fix this issue ? Wordpress version (5.5) (https://wptavern.com/major-jquery-changes-on-the-way-for-wordpress-5-5-and-beyond) removes jquery migrate.

**Comment by them-es** [comment]
Hi!

Could you elaborate further. The current version of the Bootstrap Starter Theme does not have any dependencies and our Demo instance https://them.es/starter-bootstrap which already runs on WordPress 5.5 (without the jQuery Migrate Helper Plugin) works as expected.
Please check for conflicts with installed WordPress Plugins by temporarily deactivating all Plugins. If the conflict still exists it would be great if you could share a weblink or at least more information to help reproduce your issue.

Thanks.

**Comment by davidhbrown** [comment]
Might also be worth mentioning that Bootstrap 5 has itself [dropped its dependency on jQuery](https://getbootstrap.com/docs/5.1/migration/) although it still needs its own JS bundle (including Popper v2.x).

**Comment by them-es** [comment]
@davidhbrown That's right. jQuery dependency has been removed a while ago in this theme (see empty `array()` in https://github.com/them-es/themes-starter-bootstrap/blob/main/functions.php#L489) as it's not required anymore when using Bootstrap v5.

Going to close this issue!
