### ISSUE TITLE
WordPress 6.01 Breaks Menu

### ISSUE THREAD

**Issue by PieterB22** [them-es/themes-starter#21]
Busy using the bootstrap theme to build a website for a client. I have noticed that menu items are not active and they are all added as custom link menu types. Any class changes to them are also not saved. I suspect WordPress changed something in the version 6 update that is breaking the Nav_Walker class.

I used this link to generate a new base theme today: https://them.es/starter-bootstrap/

Please see image below:
![image](https://user-images.githubusercontent.com/53510724/185102140-efa5eed5-8cf9-40be-8a40-e56bb08c9dcd.png)

**Comment by them-es** [comment]
Hi @PieterB22,

unfortunately the bug cannot be reproduced on our side. Below you can see a screenshot of the main menu of https://them.es/starter-bootstrap/ running on WordPress 6.0.1

![image](https://user-images.githubusercontent.com/10208534/185616176-77e87b41-dc9d-4711-a832-ddb33a34f39f.png)

We even tested it on a different system. Everything worked as expected!

**Comment by PieterB22** [comment]
Thanks for checking this for me. I went back to check everything on my side after seeing your reply. Turns out the issue was that my docker container got a bit corrupted.
