### ISSUE TITLE
wordpresscom include

### ISSUE THREAD

**Issue by Deele** [them-es/themes-starter#23]
In [functions.php](https://github.com/them-es/themes-starter-bootstrap/blob/13dbb03224058bff283cdbb638bd98199570922e/functions.php#L19-L22) there is require of file, that does not exist.

There is [wpcom.php](/them-es/themes-starter-bootstrap/blob/main/inc/wpcom.php) file, but no `wordpresscom.php`.

**Comment by them-es** [comment]
Thanks for the heads up @Deele 
Actually this reference is not really needed and has been removed in https://github.com/them-es/themes-starter-bootstrap/commit/b98388d81eb81be3a32233deb148db55121afada
