### ISSUE TITLE
Use of content width

### ISSUE THREAD

**Issue by Deele** [them-es/themes-starter#24]
In [functions.php](https://github.com/them-es/themes-starter-bootstrap/blob/13dbb03224058bff283cdbb638bd98199570922e/functions.php#L31) there is definition of `$content_width`, but I can't find where it is used.

**Comment by them-es** [comment]
You're right @Deele - thanks again.
A bugfix has been pushed in https://github.com/them-es/themes-starter-bootstrap/commit/dca87e1bb5575277e761fafb2f8d64aa585a079e
