### ISSUE TITLE
Inconsistent use of curly braces for implications

### ISSUE THREAD

**Issue by Deele** [them-es/themes-starter#25]
There are many places where colon + endif is used for implication block, but right next to it, there is curly brace one, like in [functions.php](https://github.com/them-es/themes-starter-bootstrap/blob/13dbb03224058bff283cdbb638bd98199570922e/functions.php#L95).

Use colon + endif only in PHP+HTML files, use curly braces in pure PHP files.

Bad:

```php
/**
 * Add new User fields to Userprofile.
 *
 * @since v1.0
 */
if ( ! function_exists( 'themes_starter_add_user_fields' ) ) :
	// [...]
endif;


/**
 * Test if a page is a blog page.
 * if ( is_blog() ) { ... }
 *
 * @since v1.0
 */
function is_blog() {
	// [...]
}
```

Good:

```php
/**
 * Add new User fields to Userprofile.
 *
 * @since v1.0
 */
if ( ! function_exists( 'themes_starter_add_user_fields' ) )  {
	// [...]
}


/**
 * Test if a page is a blog page.
 * if ( is_blog() ) { ... }
 *
 * @since v1.0
 */
function is_blog() {
	// [...]
}
```

**Comment by them-es** [comment]
Applying coding standards is essential and your remarks make sense. Thanks again @Deele
An updates has been pushed in https://github.com/them-es/themes-starter-bootstrap/commit/6879bc204e9985348d9dad9ffcda2290bd9d719c
