### ISSUE TITLE
Critical Error Caused by Footer

### ISSUE THREAD

**Issue by tkweb92** [them-es/themes-starter#27]
I am new to this so apologies if something I have done incorrectly has caused this but I don't believe so.

After installing the theme every page on the site shows this error:

> Parse error: syntax error, unexpected ')' in /home/xxx/public_html/xxx/wp-content/themes/xxx/footer.php on line 39
> There has been a critical error on this website.

I removed the comma on line 38 of [footer.php](https://github.com/them-es/themes-starter-bootstrap/blob/a326af152d3272ee5ffbca9b67fde2f0c779fb8a/footer.php#L38) and that fixes the issue.

https://github.com/them-es/themes-starter-bootstrap/blob/a326af152d3272ee5ffbca9b67fde2f0c779fb8a/footer.php#L24-L40

**Comment by them-es** [comment]
Thanks for the heads-up @tkweb92 
The trailing comma was not supposed to be here and it has been fixed in the latest commit!
