### ISSUE TITLE
Color modes not work

### ISSUE THREAD

**Issue by yduke** [them-es/themes-starter#28]
Color modes are added in bootstrap 5.3.0: [https://getbootstrap.com/docs/5.3/customize/color-modes/#dark-mode]( https://getbootstrap.com/docs/5.3/customize/color-modes/#dark-mode)
 But when I try to add `data-bs-theme="dark"` in header.php in `<html>` tag, it is not working as  expacted.

Any help would be appreciated. Thank  you.

**Comment by them-es** [comment]
@yduke Please use the updated main.scss and make sure to enable dark-mode support by adding `$enable-dark-mode: true;`
https://github.com/them-es/themes-starter-bootstrap/blob/main/assets/main.scss#L16

**Comment by yduke** [comment]
Thank you, after change the option and npm rebuild, it worked like a charm.
Thanks alot!
