### ISSUE TITLE
Css

### ISSUE THREAD

**Issue by akshat009** [them-es/themes-starter#29]
Where to add custom css

**Comment by them-es** [comment]
@akshat009 This is not the right place for general support requests. Please refer to the official WordPress documentation https://wordpress.org/documentation/ (CSS article: https://wordpress.org/documentation/article/css/) to find what you need.

**Comment by akshat009** [comment]
Your theme states don't override style.css file as per WordPress standard all theme css should be written in style.css

**Comment by them-es** [comment]
@akshat009 Please have a look at the documentation: https://github.com/them-es/themes-starter-bootstrap#task-automation
You need to install some required NPM dependencies first and compile `/assets/main.scss` afterwards.

For general information on SASS preprocessing you can lookup https://sass-lang.com/guide

**Comment by akshat009** [comment]
Thanks
