### ISSUE TITLE
"npm install" warnings and errors

### ISSUE THREAD

**Issue by anyway** [them-es/themes-starter#3]
I'm getting a couple of warnings and errors from `$ npm install` (node.js v14.17.1):

After `$ npm audit fix` the console outputs:

fixed 0 of 7 vulnerabilities in 1327 scanned packages
  4 vulnerabilities required manual review and could not be updated
  3 package updates for 3 vulnerabilities involved breaking changes

Here's the full `$ npm install` installation protocoll
(sorry, but github formats parts of the code, because of the quotation marks)
↓-----------------------------------------------------------------------↓ 

> fsevents@1.2.13 install /fakepath/node_modules/glob-watcher/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/fakepath/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/fakepath/.nvm/versions/node/v12.10.0/bin/node" "/Users/fakepath/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /fakepath/node_modules/glob-watcher/node_modules/fsevents
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> fsevents@1.2.13 install /fakepath/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/fakepath/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/fakepath/.nvm/versions/node/v12.10.0/bin/node" "/Users/fakepath/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /fakepath/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> node-sass@4.14.1 install /fakepath/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/fakepath/.npm/node-sass/4.14.1/darwin-x64-72_binding.node

> node-sass@4.14.1 postinstall /fakepath/node_modules/node-sass
> node scripts/build.js

Binary found at /fakepath/node_modules/node-sass/vendor/darwin-x64-72/binding.node
Testing binary
Binary is fine
added 1326 packages from 822 contributors and audited 1327 packages in 15.546s

49 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (1 low, 4 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by codeinforest** [comment]
@anyway What is your node version?
If > 14, please downgrade to 14, hope it helpful!

**Comment by aquantech** [comment]
@anyway Try to remove xcode-select and re-install it. Hope it helpful.

**Comment by them-es** [comment]
All outdated dependencies have been updated now:
https://github.com/them-es/themes-starter-bootstrap/blob/main/package.json#L18:L34

Could you give it another try?

Please clean the cache beforehand `npm cache clean --force`
