### ISSUE TITLE
Package vulnerabilities

### ISSUE THREAD

**Issue by rohankleem** [them-es/themes-starter#30]
Running npm install against the supplied package.json file (in the theme download), gives
"6 high severity vulnerabilities"

Any suggestions on how this should be handled? Forcing fixes just makes it worse unfortunately

In particular:
glob-parent  <5.1.2
Severity: high
glob-parent before 5.1.2 vulnerable to Regular Expression Denial of Service in enclosure regex - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix --force`
Will install gulp@3.9.1, which is a breaking change
node_modules/glob-stream/node_modules/glob-parent
node_modules/glob-watcher/node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/glob-watcher/node_modules/chokidar
    glob-watcher  3.0.0 - 5.0.5
    Depends on vulnerable versions of chokidar
    node_modules/glob-watcher
  glob-stream  5.3.0 - 6.1.0
  Depends on vulnerable versions of glob-parent
  node_modules/glob-stream
    vinyl-fs  2.4.2 - 3.0.3
    Depends on vulnerable versions of glob-stream
    node_modules/vinyl-fs
      gulp  >=4.0.0
      Depends on vulnerable versions of glob-watcher
      Depends on vulnerable versions of vinyl-fs
      node_modules/gulp

**Comment by them-es** [comment]
> Any suggestions on how this should be handled?

Unfortunately not. But replacing the current Gulp workflow with a more future-proof setup (probably Webpack handled by the [@wordpress/scripts](https://www.npmjs.com/package/@wordpress/scripts) package) is on our roadmap.

Stay tuned!

**Comment by them-es** [comment]
@rohankleem The old Gulp/webpack workflow of all Starter Themes now has been replaced with the future-proof `@wordpress/scripts` package (which uses webpack under the hood and is maintained by the Gutenberg community):
https://them.es/support/2023/08/18/starter-themes-with-a-new-build-workflow/

Feel free to give it a try!
