### ISSUE TITLE
Dart SASS: Using / for division is deprecated

### ISSUE THREAD

**Issue by davidhbrown** [them-es/themes-starter#5]
A couple instances of `$grid-gutter-width/2;` will eventually need replacing by `math.div($grid-gutter-width, 2)`. Will also need `@use "sass:math";` before any imports.
(PR provided if you're ready for this.)

**Comment by them-es** [comment]
This has been fixed in https://github.com/them-es/themes-starter-bootstrap/commit/cc74a3722d7fbe349e2ac657d49cf97eac120e17#diff-3a56bfc93d029f425c8fbd43b763c034935c43cea022202ea319c19555a7eb8a
