### ISSUE TITLE
index.php is defined as a custom page template.. Why?

### ISSUE THREAD

**Issue by flaming-mind** [them-es/themes-starter#9]
The default file index.php is defined as custom page template as seen it's top comments.

Why was this done? 

It adds confusion to the WordPress template hierarchy. I don't feel it should be done this way. The index.php should be the final fall back if all other template files are not found.

Was the intention is use the index.php file as a selectable template for the Page Post types? If that is the case, it doesn't work correctly. When choosing it as a template for Page Post types in Dashboard, the blog index won't appear. Only the pages content appears , not the main index posts.

I think the better solution would to remove the comments on the top of index.php and create a new custom template file for blog post layout if needed. Some codes changes would have to be done to the loop.

Any one experienced this issue before?

Here are some links that could be helpful to get a better understanding:

https://wordpress.stackexchange.com/questions/251205/creating-custom-blog-page-template-the-right-way
https://developer.wordpress.org/themes/basics/template-hierarchy/

**Comment by them-es** [comment]
Thanks for reaching out @flaming-mind

`index.php` is not meant to be used as a page template at first hand — only if you need to add content/blocks before the loop  (See: https://them.es/starter-bootstrap/blog/) which is a common client request.

The Blog index page needs to be selected as your *Posts page* under `/wp-admin/options-reading.php` which is documented here: https://them.es/setup/
